version: "3"

networks:
  net:

services:
  task-management:
    container_name: zero-hero.task-management-service
    build:
      context: ./task-management
      dockerfile: Dockerfile
    volumes:
      - ./task-management:/app
      - /app/node_modules
    env_file:
      - task-management/.env
    depends_on:
      - postgres-db
      - auth-service
    ports:
      - 34000:3000
      - 9230:9230
    networks:
      - net

  auth-service:
    container_name: zero-hero.auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    env_file:
      - auth-service/.env
    depends_on:
      - postgres-db
    ports:
      - 34001:3000
      - 9231:9231
    networks:
      - net

  postgres-db:
    image: postgres:12.0-alpine
    container_name: zero-hero.app-db
    ports:
      - 50432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1123
      POSTGRES_DB: app-db
    networks:
      - net

volumes:
  postgres:
